---
micronaut:
    application:
        name: micronaut-gorm-postgresql-example
                
#Uncomment to set server port
#    server:
#        port: 8080

---
datasources.default: {}
---
hibernate:
  hbm2ddl:
    auto: update
  cache:
    queries: false
    use_second_level_cache: true
    use_query_cache: false
    region.factory_class: org.hibernate.cache.ehcache.SingletonEhCacheRegionFactory